server:
    port: 8080

spring:
  application:
    name: crawler
  datasource:
    druid:
      url: jdbc:mysql://192.168.0.13:3306/films?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
      initialSize: 10
      minIdle: 5
      maxActive: 30
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat,wall
      maxPoolPreparedStatementPerConnectionSize: 30
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      pool-prepared-statements: true
      stat-view-servlet:
        enabled: true
        login-username: druid
        login-password: druid
        url-pattern: /druid/**
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/**'
        url-pattern: /druid/**
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: true
    enabled: true
    servlet:
      content-type: text/html
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  mapper-locations: classpath*:/mybatis/mappers/*.xml
logging:
  level:
    com.baomidou.mybatis-plus: debug
    org.mybatis: debug
